In [5]:
import numpy as np 



0.49999999999999994

In [14]:
print(np.zeros((3,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
sides = 12
vertices = np.zeros((3,sides))+np.arange(sides)
vertices = vertices*10

alfa = np.array([1,2,3])
#mul = np.arange(sides)
print(vertices)

print(np.shape(alfa))
print(np.shape(alfa)[0])
beta= np.reshape(alfa, (1,np.shape(alfa)[0]))
print(beta)

vertices = vertices + beta.T
print(vertices)

#print(mul)
#vertices = vertices+mul
#print(vertices)

[[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110.]
 [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110.]
 [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110.]]
(3,)
3
[[1 2 3]]
[[  1.  11.  21.  31.  41.  51.  61.  71.  81.  91. 101. 111.]
 [  2.  12.  22.  32.  42.  52.  62.  72.  82.  92. 102. 112.]
 [  3.  13.  23.  33.  43.  53.  63.  73.  83.  93. 103. 113.]]


In [47]:
np.set_printoptions(suppress=True, precision=6)
 
sides = 20

angle = np.radians(360/sides)
vertices = np.zeros((2,sides))+np.arange(sides)
vertices = vertices*angle
vertices[0,:] = np.cos(vertices[0,:])
vertices[1,:] = np.sin(vertices[1,:])
outra_matriz = np.zeros((1,np.shape(vertices)[1]))
alfa = np.concatenate((vertices,outra_matriz),axis=0)
print(outra_matriz)
print(vertices)
print(alfa)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 1.        0.951057  0.809017  0.587785  0.309017  0.       -0.309017
  -0.587785 -0.809017 -0.951057 -1.       -0.951057 -0.809017 -0.587785
  -0.309017 -0.        0.309017  0.587785  0.809017  0.951057]
 [ 0.        0.309017  0.587785  0.809017  0.951057  1.        0.951057
   0.809017  0.587785  0.309017  0.       -0.309017 -0.587785 -0.809017
  -0.951057 -1.       -0.951057 -0.809017 -0.587785 -0.309017]]
[[ 1.        0.951057  0.809017  0.587785  0.309017  0.       -0.309017
  -0.587785 -0.809017 -0.951057 -1.       -0.951057 -0.809017 -0.587785
  -0.309017 -0.        0.309017  0.587785  0.809017  0.951057]
 [ 0.        0.309017  0.587785  0.809017  0.951057  1.        0.951057
   0.809017  0.587785  0.309017  0.       -0.309017 -0.587785 -0.809017
  -0.951057 -1.       -0.951057 -0.809017 -0.587785 -0.309017]
 [ 0.        0.        0.        0.        0.        0.        0.
   0.        0.        0.        0.      