In [16]:
import numpy as np 
import time


In [3]:
bla = np.zeros((4,4))
bla[0,3] = 1
print(bla)

[[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
a = np.eye(3)
b = np.eye(3)
c = b*5
d = a+10
print(c)
print(d)
print(c*d)
print(np.dot(c,d))

[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]
[[11. 10. 10.]
 [10. 11. 10.]
 [10. 10. 11.]]
[[55.  0.  0.]
 [ 0. 55.  0.]
 [ 0.  0. 55.]]
[[55. 50. 50.]
 [50. 55. 50.]
 [50. 50. 55.]]


In [33]:
t_umlinhaS = 0
t_vlinhaS = 0
speedupUm = 0
speedupVa = 0
for i in range(100):
    t0=time.time()
    for i in range(1,1000000):
        b=i
        c=i+1
        d=i
        e=i+1
        f=2*i
        g=i

        a=((b*c)+(d*e))/(f-g)
    t1=time.time()
    t_umlinha = t1-t0

    t0=time.time()
    for i in range(1,1000000):
        b=i
        c=i+1
        d=i
        e=i+1
        f=2*i
        g=i

        a=b
        a*=c
        a+=(d*e)
        a/=(f-g)
    t1=time.time()
    t_vlinha = t1-t0

    if t_vlinha<t_umlinha:
        t_umlinhaS += 1
        speedupUm += t_umlinha/t_vlinha
    else:
        t_vlinhaS +=1
        speedupVa += t_vlinha/t_umlinha
    
print(f"Vitorias Um Linha: {t_umlinhaS}")
print(f"Speedup Medio: {speedupUm/t_umlinhaS}")
print(f"Vitorias Um Linha: {t_vlinhaS}")
print(f"Speedup Medio: {speedupVa/t_vlinhaS}")

Vitorias Um Linha: 2
Speedup Medio: 1.003462358649138
Vitorias Um Linha: 98
Speedup Medio: 1.167749041050426


In [34]:
a = np.array([1,2,3])
print(np.shape(a))

(3,)


In [36]:
b=np.reshape(a, (1,np.shape(a)[0])).T
print(np.shape(b))

(3, 1)


In [39]:
c = np.array([[1],[2],[3]])
print(np.array_equal(b,c))

True


In [14]:
print(np.zeros((3,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
sides = 12
vertices = np.zeros((3,sides))+np.arange(sides)
vertices = vertices*10

alfa = np.array([1,2,3])
#mul = np.arange(sides)
print(vertices)

print(np.shape(alfa))
print(np.shape(alfa)[0])
beta= np.reshape(alfa, (1,np.shape(alfa)[0]))
print(beta)

vertices = vertices + beta.T
print(vertices)

#print(mul)
#vertices = vertices+mul
#print(vertices)

[[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110.]
 [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110.]
 [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110.]]
(3,)
3
[[1 2 3]]
[[  1.  11.  21.  31.  41.  51.  61.  71.  81.  91. 101. 111.]
 [  2.  12.  22.  32.  42.  52.  62.  72.  82.  92. 102. 112.]
 [  3.  13.  23.  33.  43.  53.  63.  73.  83.  93. 103. 113.]]


In [47]:
np.set_printoptions(suppress=True, precision=6)
 
sides = 20

angle = np.radians(360/sides)
vertices = np.zeros((2,sides))+np.arange(sides)
vertices = vertices*angle
vertices[0,:] = np.cos(vertices[0,:])
vertices[1,:] = np.sin(vertices[1,:])
outra_matriz = np.zeros((1,np.shape(vertices)[1]))
alfa = np.concatenate((vertices,outra_matriz),axis=0)
print(outra_matriz)
print(vertices)
print(alfa)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 1.        0.951057  0.809017  0.587785  0.309017  0.       -0.309017
  -0.587785 -0.809017 -0.951057 -1.       -0.951057 -0.809017 -0.587785
  -0.309017 -0.        0.309017  0.587785  0.809017  0.951057]
 [ 0.        0.309017  0.587785  0.809017  0.951057  1.        0.951057
   0.809017  0.587785  0.309017  0.       -0.309017 -0.587785 -0.809017
  -0.951057 -1.       -0.951057 -0.809017 -0.587785 -0.309017]]
[[ 1.        0.951057  0.809017  0.587785  0.309017  0.       -0.309017
  -0.587785 -0.809017 -0.951057 -1.       -0.951057 -0.809017 -0.587785
  -0.309017 -0.        0.309017  0.587785  0.809017  0.951057]
 [ 0.        0.309017  0.587785  0.809017  0.951057  1.        0.951057
   0.809017  0.587785  0.309017  0.       -0.309017 -0.587785 -0.809017
  -0.951057 -1.       -0.951057 -0.809017 -0.587785 -0.309017]
 [ 0.        0.        0.        0.        0.        0.        0.
   0.        0.        0.        0.      