In [1]:
import numpy as np 
import time


In [4]:
def soma(x,y):
    return x+y
def sub(x,y):
    return x-y
def mult(x,y):
    return x*y

def funcaozona(p,q,r,s,t,u):
    a=soma(p,q)
    b=sub(s,r)
    c=mult(a,b)
    d=soma(c,t)
    e=sub(u,d)
    return e

t0=time.time()
f=funcaozona(1,2,3,4,5,6)
t1=time.time()
print(t1-t0)

def funcaozona2(p,q,r,s,t,u):
    a=p+q
    b=s-r
    c=a*b
    d=c+t
    e=u-d
    return e

t0=time.time()
f=funcaozona2(1,2,3,4,5,6)
t1=time.time()
print(t1-t0)

0.0004296302795410156
0.0001888275146484375


In [15]:
x=np.zeros((4,6))+np.arange(6)
x[3,0]=1
x[0,:]*=10
x[1,:]*=-10
x[2,:]*=0.1
print(x)
x/=x[3,:]
print(x)

[[  0.   10.   20.   30.   40.   50. ]
 [ -0.  -10.  -20.  -30.  -40.  -50. ]
 [  0.    0.1   0.2   0.3   0.4   0.5]
 [  1.    1.    2.    3.    4.    5. ]]
[[  0.   10.   10.   10.   10.   10. ]
 [ -0.  -10.  -10.  -10.  -10.  -10. ]
 [  0.    0.1   0.1   0.1   0.1   0.1]
 [  1.    1.    1.    1.    1.    1. ]]


In [6]:
VRPx=3
VRPy=2
VRPz=1
Px=2
Py=1
Pz=0
Yx=0
Yy=1
Yz=0

In [200]:
t0=time.time()
T = np.eye(4)
T[:3,3] = -VRP
R = np.eye(4)
R[0,:3] = np.cross(v,n)
R[1,:3] = v
R[2,:3] = n
F=np.dot(R,T)
t1=time.time()
print(t1-t0)

0.0023093223571777344


In [201]:
t0=time.time()
R = np.eye(4)
R[0,:3] = np.cross(v,n)
R[1,:3] = v
R[2,:3] = n
R[0,3] = -np.dot(VRP,u)
R[1,3] = -np.dot(VRP,v)
R[2,3] = -np.dot(VRP,n)
t1=time.time()
print(t1-t0)

0.0018029212951660156


In [53]:
VRP = np.array([VRPx, VRPy, VRPz])
Y = np.array([Yx, Yy, Yz])
N = VRP-np.array([Px, Py, Pz])
n = N/(np.linalg.norm(N))
V = Y-np.dot(np.dot(Y,n),n)
v = V/(np.linalg.norm(V))
u = np.cross(v,n)
T = np.eye(4)
T[:3,3] = -VRP
R = np.concatenate((np.concatenate((np.stack((u,v,n), axis=0),np.zeros((1,3)))),np.zeros((4,1))),axis=1)
R[3,3]=1


In [202]:
-1%3

2

In [173]:
t0=time.time()
R = np.concatenate((np.concatenate((np.stack((u,v,n), axis=0),np.zeros((1,3)))),np.zeros((4,1))),axis=1)
R[3,3]=1
t1=time.time()
print(t1-t0)

0.0011684894561767578


In [179]:
t0=time.time()
R=np.eye(4)
R[0,:3]=u
R[1,:3]=v
R[2,:3]=n
t1=time.time()
print(t1-t0)

0.0003917217254638672


In [50]:
print(T)
print(R)

[[ 1.  0.  0. -3.]
 [ 0.  1.  0. -2.]
 [ 0.  0.  1. -1.]
 [ 0.  0.  0.  1.]]
[[ 0.70710678  0.         -0.70710678  0.        ]
 [-0.40824829  0.81649658 -0.40824829  0.        ]
 [ 0.57735027  0.57735027  0.57735027  0.        ]
 [ 0.          0.          0.          1.        ]]


In [3]:
bla = np.zeros((4,4))
bla[0,3] = 1
print(bla)

[[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
a = np.eye(3)
b = np.eye(3)
c = b*5
d = a+10
print(c)
print(d)
print(c*d)
print(np.dot(c,d))

[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]
[[11. 10. 10.]
 [10. 11. 10.]
 [10. 10. 11.]]
[[55.  0.  0.]
 [ 0. 55.  0.]
 [ 0.  0. 55.]]
[[55. 50. 50.]
 [50. 55. 50.]
 [50. 50. 55.]]


In [33]:
t_umlinhaS = 0
t_vlinhaS = 0
speedupUm = 0
speedupVa = 0
for i in range(100):
    t0=time.time()
    for i in range(1,1000000):
        b=i
        c=i+1
        d=i
        e=i+1
        f=2*i
        g=i

        a=((b*c)+(d*e))/(f-g)
    t1=time.time()
    t_umlinha = t1-t0

    t0=time.time()
    for i in range(1,1000000):
        b=i
        c=i+1
        d=i
        e=i+1
        f=2*i
        g=i

        a=b
        a*=c
        a+=(d*e)
        a/=(f-g)
    t1=time.time()
    t_vlinha = t1-t0

    if t_vlinha<t_umlinha:
        t_umlinhaS += 1
        speedupUm += t_umlinha/t_vlinha
    else:
        t_vlinhaS +=1
        speedupVa += t_vlinha/t_umlinha
    
print(f"Vitorias Um Linha: {t_umlinhaS}")
print(f"Speedup Medio: {speedupUm/t_umlinhaS}")
print(f"Vitorias Um Linha: {t_vlinhaS}")
print(f"Speedup Medio: {speedupVa/t_vlinhaS}")

Vitorias Um Linha: 2
Speedup Medio: 1.003462358649138
Vitorias Um Linha: 98
Speedup Medio: 1.167749041050426


In [34]:
a = np.array([1,2,3])
print(np.shape(a))

(3,)


In [36]:
b=np.reshape(a, (1,np.shape(a)[0])).T
print(np.shape(b))

(3, 1)


In [39]:
c = np.array([[1],[2],[3]])
print(np.array_equal(b,c))

True


In [14]:
print(np.zeros((3,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
sides = 12
vertices = np.zeros((3,sides))+np.arange(sides)
vertices = vertices*10

alfa = np.array([1,2,3])
#mul = np.arange(sides)
print(vertices)

print(np.shape(alfa))
print(np.shape(alfa)[0])
beta= np.reshape(alfa, (1,np.shape(alfa)[0]))
print(beta)

vertices = vertices + beta.T
print(vertices)

#print(mul)
#vertices = vertices+mul
#print(vertices)

[[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110.]
 [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110.]
 [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110.]]
(3,)
3
[[1 2 3]]
[[  1.  11.  21.  31.  41.  51.  61.  71.  81.  91. 101. 111.]
 [  2.  12.  22.  32.  42.  52.  62.  72.  82.  92. 102. 112.]
 [  3.  13.  23.  33.  43.  53.  63.  73.  83.  93. 103. 113.]]


In [47]:
np.set_printoptions(suppress=True, precision=6)
 
sides = 20

angle = np.radians(360/sides)
vertices = np.zeros((2,sides))+np.arange(sides)
vertices = vertices*angle
vertices[0,:] = np.cos(vertices[0,:])
vertices[1,:] = np.sin(vertices[1,:])
outra_matriz = np.zeros((1,np.shape(vertices)[1]))
alfa = np.concatenate((vertices,outra_matriz),axis=0)
print(outra_matriz)
print(vertices)
print(alfa)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 1.        0.951057  0.809017  0.587785  0.309017  0.       -0.309017
  -0.587785 -0.809017 -0.951057 -1.       -0.951057 -0.809017 -0.587785
  -0.309017 -0.        0.309017  0.587785  0.809017  0.951057]
 [ 0.        0.309017  0.587785  0.809017  0.951057  1.        0.951057
   0.809017  0.587785  0.309017  0.       -0.309017 -0.587785 -0.809017
  -0.951057 -1.       -0.951057 -0.809017 -0.587785 -0.309017]]
[[ 1.        0.951057  0.809017  0.587785  0.309017  0.       -0.309017
  -0.587785 -0.809017 -0.951057 -1.       -0.951057 -0.809017 -0.587785
  -0.309017 -0.        0.309017  0.587785  0.809017  0.951057]
 [ 0.        0.309017  0.587785  0.809017  0.951057  1.        0.951057
   0.809017  0.587785  0.309017  0.       -0.309017 -0.587785 -0.809017
  -0.951057 -1.       -0.951057 -0.809017 -0.587785 -0.309017]
 [ 0.        0.        0.        0.        0.        0.        0.
   0.        0.        0.        0.      